import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { client } from '../lib/api'
import type { BookingGroup, Ticket } from '../types'

export function ConfirmationPage() { const { bookingGroupId = '' } = useParams(); const booking = useQuery({ queryKey: ['booking', bookingGroupId], queryFn: () => client.booking(bookingGroupId) }); if (booking.isLoading) return <main className="page-shell"><div className="skeleton detail-skeleton" /></main>; if (booking.isError || !booking.data) return <main className="page-shell"><div className="empty-state"><h1>We couldn't find that confirmation.</h1><Link className="primary inline" to="/my-bookings">View my bookings</Link></div></main>; return <main className="page-shell confirmation"><section className="confirmation-hero"><p className="success-icon">✓</p><p className="eyebrow">BOOKING CONFIRMED</p><h1>Your seats are reserved.</h1><p>Reference <strong>{booking.data.pnr}</strong> · Your payment was simulated successfully.</p></section><BookingGroupCard group={booking.data} showCancel={false} /><div className="confirmation-actions"><Link className="primary inline" to="/my-bookings">Manage my booking</Link><Link className="outline-button" to="/">Find another bus</Link></div></main> }

export function MyBookingsPage() { const bookings = useQuery({ queryKey: ['bookings'], queryFn: client.bookings }); return <main className="page-shell"><header className="booking-header"><p className="eyebrow">YOUR TRAVEL DESK</p><h1>My bookings</h1><p>Every checkout stays together. You can cancel one ticket without changing the rest.</p></header>{bookings.isLoading && <><div className="skeleton card-skeleton" /><div className="skeleton card-skeleton" /></>}{bookings.isError && <div className="empty-state"><h2>We couldn't load your bookings.</h2><button className="primary" onClick={() => bookings.refetch()}>Try again</button></div>}{bookings.data?.length === 0 && <div className="empty-state"><h2>No trips booked yet.</h2><p>Start with a route that feels like a good idea.</p><Link className="primary inline" to="/">Find buses</Link></div>}{bookings.data?.map((group) => <BookingGroupCard key={group.id} group={group} showCancel />)}</main> }

function BookingGroupCard({ group, showCancel }: { group: BookingGroup; showCancel: boolean }) { const [pending, setPending] = useState<Ticket | null>(null); const queryClient = useQueryClient(); const cancellation = useMutation({ mutationFn: client.cancel, onSuccess: (updated) => { queryClient.setQueryData(['bookings'], (old: BookingGroup[] | undefined) => old?.map((item) => item.id === updated.id ? updated : item)); queryClient.setQueryData(['booking', updated.id], updated); setPending(null) } }); return <article className="booking-group"><header><div><span className={`status ${group.status.toLowerCase()}`}>{group.status.replaceAll('_', ' ')}</span><h2>{group.pnr}</h2><p>Booked {new Date(group.createdAt).toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', day: 'numeric', month: 'short', year: 'numeric' })}</p></div><strong>₹{group.tickets.reduce((total, ticket) => total + ticket.totalFare, 0).toLocaleString('en-IN')}</strong></header><div className="tickets">{group.tickets.map((ticket) => <div className="ticket" key={ticket.id}><div className="ticket-route"><b>{ticket.trip.route.source.name} → {ticket.trip.route.destination.name}</b><span>{ticket.trip.travelDate} · {ticket.trip.departureTime} · Seat {ticket.seatNumber}</span></div><div><b>{ticket.passengerName}</b><span>{ticket.status === 'CANCELLED' ? `Cancelled · Mock refund ₹${ticket.refundAmount}` : 'Active ticket'}</span></div>{showCancel && ticket.status === 'ACTIVE' && <button className="danger-button" onClick={() => setPending(ticket)}>Cancel ticket</button>}</div>)}</div>{pending && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="cancel-title"><p className="eyebrow">CANCEL TICKET</p><h2 id="cancel-title">Cancel seat {pending.seatNumber}?</h2><p>You'll see a simulated refund of <strong>₹{Math.round(pending.totalFare * .9)}</strong>. The seat will become available again.</p><p className="muted">The trip’s visible cancellation deadline is six hours before departure.</p>{cancellation.isError && <p className="form-error">This ticket can no longer be cancelled.</p>}<div className="modal-actions"><button className="outline-button" onClick={() => setPending(null)}>Keep ticket</button><button className="danger-button" disabled={cancellation.isPending} onClick={() => cancellation.mutate(pending.id)}>{cancellation.isPending ? 'Cancelling…' : 'Confirm cancellation'}</button></div></section></div>}</article> }
