import { useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, ArrowRightLeft, BusFront, CalendarDays, Clock3, MapPin, Search, Sparkles } from 'lucide-react'
import { client } from '../lib/api'
import type { ParsedSearch } from '../types'
import heroImage from '../assets/voyagebus-hero.jpg'

const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata' }).format(new Date())
function toSearch(values: Record<string, string | number | boolean | null>) { const params = new URLSearchParams(); Object.entries(values).forEach(([key, value]) => { if (value !== null && value !== '') params.set(key, String(value)) }); return `/search?${params}` }
const popular = [['Hyderabad', 'Bengaluru', 'From ₹699'], ['Bengaluru', 'Chennai', 'From ₹549'], ['Kochi', 'Thiruvananthapuram', 'From ₹399']]

export function HomePage() {
  const navigate = useNavigate(); const [source, setSource] = useState('Hyderabad'); const [destination, setDestination] = useState('Vijayawada'); const [date, setDate] = useState(today); const [query, setQuery] = useState(''); const [parsed, setParsed] = useState<ParsedSearch | null>(null)
  const parser = useMutation({ mutationFn: client.parse, onSuccess: setParsed }); const routes = useQuery({ queryKey: ['routes'], queryFn: client.routes }); const cities = [...new Set(routes.data?.flatMap((route) => [route.source.name, route.destination.name]) ?? [])].sort()
  const search = () => navigate(toSearch({ source, destination, date })); const updateParsed = (key: keyof ParsedSearch, value: string) => setParsed((current) => current ? { ...current, [key]: value || null } : current); const useParsed = () => { if (!parsed?.source || !parsed.destination) return; navigate(toSearch({ source: parsed.source, destination: parsed.destination, date: parsed.date || today, maxPrice: parsed.maxPrice, isAc: parsed.isAc, busType: parsed.busType, departure: parsed.timePreference })) }
  return <main><datalist id="supported-cities">{cities.map((city) => <option value={city} key={city} />)}</datalist>
    <section className="voyage-hero" style={{ '--hero-image': `url(${heroImage})` } as React.CSSProperties}><div className="hero-copy"><span className="hero-label"><BusFront /> South India, connected</span><h1>The right bus.<br />The seat you want.</h1><p>Compare dependable operators, choose your seat, and keep every trip in one place.</p></div>
      <section className="search-panel" aria-labelledby="trip-search-title"><div className="search-panel-title"><div><span>Book a bus</span><h2 id="trip-search-title">Where are you heading?</h2></div><small>One way</small></div><div className="manual-search"><label><span><MapPin /> From</span><input list="supported-cities" value={source} onChange={(e) => setSource(e.target.value)} /></label><button className="swap" aria-label="Swap origin and destination" onClick={() => { setSource(destination); setDestination(source) }}><ArrowRightLeft /></button><label><span><MapPin /> To</span><input list="supported-cities" value={destination} onChange={(e) => setDestination(e.target.value)} /></label><label><span><CalendarDays /> Travel date</span><input type="date" min={today} value={date} onChange={(e) => setDate(e.target.value)} /></label><button className="primary" onClick={search}><Search /> Search buses</button></div></section>
    </section>
    <section className="popular-routes"><header><div><h2>Popular routes</h2><p>Frequently searched journeys from the routes currently available.</p></div></header><div className="route-list">{popular.map(([from,to,fare]) => <button key={to} onClick={() => navigate(toSearch({ source: from, destination: to, date: today }))}><span className="route-icon"><BusFront /></span><span><strong>{from} <ArrowRight /> {to}</strong><small><Clock3 /> Daily services</small></span><b>{fare}</b><ArrowRight /></button>)}</div></section>
    <section className="offer-strip"><div><span>FIRST BOOKING</span><strong>Save 15% on your first VoyageBus trip</strong><small>Use code <b>FIRSTVOYAGE</b> at checkout. Demo offer.</small></div><button onClick={() => { navigator.clipboard?.writeText('FIRSTVOYAGE') }}>Copy code</button></section>
    <section className="natural-search"><div><span className="feature-icon"><Sparkles /></span><div><h2>Prefer to describe your trip?</h2><p>Try “AC sleeper from Hyderabad to Bengaluru tomorrow night under ₹1,200”.</p></div></div><div className="natural-search-form"><label className="sr-only" htmlFor="ai-query">Describe your trip</label><input id="ai-query" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Describe your journey" onKeyDown={(e) => e.key === 'Enter' && query.trim() && parser.mutate(query)} /><button className="outline-button" disabled={!query.trim() || parser.isPending} onClick={() => parser.mutate(query)}>{parser.isPending ? 'Reading…' : 'Understand trip'} <ArrowRight /></button></div>{parser.isError && <p className="form-error">We could not understand that yet. Try the regular search above.</p>}{parsed && <div className="parsed-result"><div><strong>Check your trip</strong><div className="parsed-fields"><label>From<input list="supported-cities" value={parsed.source || ''} onChange={(e) => updateParsed('source', e.target.value)} /></label><label>To<input list="supported-cities" value={parsed.destination || ''} onChange={(e) => updateParsed('destination', e.target.value)} /></label><label>Date<input type="date" min={today} value={parsed.date || today} onChange={(e) => updateParsed('date', e.target.value)} /></label></div></div><button className="primary" disabled={!parsed.source || !parsed.destination} onClick={useParsed}>Show buses <ArrowRight /></button></div>}</section>
    <section className="home-note"><p>VoyageBus currently covers six seeded South India corridors. Payments and offers are simulated for this portfolio experience.</p><Link to="/register">Create an account <ArrowRight /></Link></section>
  </main>
}
